---
abstract: 'split text file to some parts(from one line start to another/same line end)'
author:
  - 'Ktat, C<< <ktat at cpan.org> >>'
  - 'Ktat <ktat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Parts
no_index:
  directory:
    - inc
    - t
resources:
  bugtracker: https://github.com/ktat/Text-Parts/issues
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git@github.com:ktat/Text-Parts.git
    web: https://github.com/ktat/Text-Parts
version: 0.02
